apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-dashboard-frontend
  namespace: health-dashboard
  labels:
    app: health-dashboard-frontend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-dashboard-frontend
  template:
    metadata:
      labels:
        app: health-dashboard-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: health-dashboard/frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: health-dashboard-frontend-config
              key: REACT_APP_API_URL
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: health-dashboard-frontend-config
              key: REACT_APP_ENVIRONMENT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: registry-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: health-dashboard-frontend-service
  namespace: health-dashboard
  labels:
    app: health-dashboard-frontend
spec:
  selector:
    app: health-dashboard-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-dashboard-frontend-hpa
  namespace: health-dashboard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-dashboard-frontend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
